# action.yml
# Github runs this:
# /usr/bin/docker run \
#   --name d120b6da334484529a49e9833ed018920_8e4337 --label 10865d --workdir /github/workspace --rm \
#   -e INPUT_ORT-ARGS -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_ACTOR \
#   -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE \
#   -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP \
#   -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e GITHUB_ACTIONS=true \
#   -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" \
#   -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/ort-scan-test/ort-scan-test":"/github/workspace" \
#   10865d:120b6da334484529a49e9833ed018920  "."
name: 'OSS Analysis'
description: 'Analyze a repository with the OSS Review Toolkit'
inputs:
    input-dir:
      description: 'ORT input directory'
      required: false
      default: '/github/workspace'
    output-dir:
      description: 'ORT results directory'
      required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - analyze
    - -i
    - ${{ inputs.input-dir }}
    - -o
    - ${{ inputs.output-dir }}
    - --allow-dynamic-versions
    - -f
    - JSON
